name: ci-build
on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ macos-latest, windows-latest, ubuntu-latest ]
        os: [ ubuntu-latest ]
    name: build-and-testing
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        name: Setup GraalVM 22.3.0
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: maven
      - name: Build & Verify Project
        run: ./mvnw verify
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

